### PR TITLE
Add PostgreSQL 9.6 with PostGIS 2.3

### LINKED ISSUE #3: The 9.5 image crashes on first startup
```
$ sudo docker-compose up postgres-95

...

postgres-95_1 | 
postgres-95_1 | 
postgres-95_1 | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00-postgis.sql
postgres-95_1 | ERROR:  could not open extension control file "/usr/share/postgresql/9.5/extension/postgis.control": No such file or directory
postgres-95_1 | ERROR:  could not open extension control file "/usr/share/postgresql/9.5/extension/postgis.control": No such file or directory
postgres-95_1 | STATEMENT:  CREATE EXTENSION postgis;
sequelize_postgres-95_1 exited with code 3
```

If I run the up command again, the container comes up fine

### PR DESCRIPTION
**Pull request by sbrunner**
also fix #3

### CODE REVIEW

**Comment by sbrunner** [comment]
@raphink The Jenkins test don't seam to works...

**Comment by sbrunner** [comment]
@raphink Why do you do a docker pull on a pull request?

**Comment by pvalsecc** [comment]
This image is out of life. We are supposed to switch to Mathieu's, no?
https://github.com/camptocamp/docker-postgresql

**Comment by sbrunner** [comment]
@pvalsecc Good to know shouldn't if be written in the Readme?

**Review by pvalsecc — APPROVED** [review]
The failing tests on jenkins are not your problem. So you can go ahead and merge.

**Pull request merged**
